config/routes.rb
Rails.application.routes.draw do

  resources :programs
  root 'welcome#index'


  devise_for :users


  resources :programs do
	 resources :analytes do
      resources :unit_lists
      resources :data_lists
      resources :mode_lists
      resources :reagent_lists
    end
  end

  resources :unit_lists do
    resources :unit_list_lines
  end

  resources :data_lists do
    resources :data_list_lines
  end

  resources :mode_lists do
    resources :mode_list_lines
  end

  resources :reagent_lists do
    resources :reagent_list_lines
  end
  

end

app/models/analyte.rb
class Analyte < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :program, optional: true
	belongs_to :reagent_list, optional: true
	belongs_to :unit_list, optional: true
	belongs_to :mode_list, optional: true
	belongs_to :data_list, optional: true
end

app/models/data_list.rb
class DataList < ApplicationRecord
	has_many :analytes
	has_many :data_list_lines, dependent: :destroy
end

app/models/data_list_line.rb
class DataListLine < ApplicationRecord
	has_many :data, dependent: :destroy
	has_many :units, dependent: :destroy
	belongs_to :data_list, optional: true
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :term, optional: true
  belongs_to :program, optional: true
  belongs_to :analyte, optional: true
  belongs_to :unit, optional: true
  belongs_to :mode, optional: true
  belongs_to :reagent, optional: true
  belongs_to :data_list_line, optional: true
end

app/models/mode.rb
class Mode < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :mode_list_line, optional: true
end

app/models/mode_list.rb
class ModeList < ApplicationRecord
	has_many :analytes
	has_many :mode_list_lines, dependent: :destroy
end

app/models/mode_list_line.rb
class ModeListLine < ApplicationRecord
	has_many :modes, dependent: :destroy
	belongs_to :mode_list, optional: true
end

app/models/program.rb
class Program < ApplicationRecord
	has_many :data, dependent: :destroy
	has_many :analytes, dependent: :destroy
end

app/models/reagent.rb
class Reagent < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :reagent_list_line, optional: true
end

app/models/reagent_list.rb
class ReagentList < ApplicationRecord
	has_many :analytes
	has_many :reagent_list_lines, dependent: :destroy
end

app/models/reagent_list_line.rb
class ReagentListLine < ApplicationRecord
	has_many :reagents, dependent: :destroy
	belongs_to :reagent_list, optional: true
end

app/models/term.rb
class Term < ApplicationRecord
	has_many :data, dependent: :destroy
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :unit_list_line, optional: true
end

app/models/unit_list.rb
class UnitList < ApplicationRecord
	has_many :analytes
	has_many :unit_list_lines, dependent: :destroy
end

app/models/unit_list_line.rb
class UnitListLine < ApplicationRecord
	belongs_to :unit_list, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :data, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/data_list_lines_controller.rb
class DataListLinesController < ApplicationController
  before_action :set_data_list_line, only: [:show, :edit, :update, :destroy]
  before_action :set_inheritenced_vars, only: [:index, :show, :new, :edit, :create, :update, :destroy]


  # GET /data_list_lines
  # GET /data_list_lines.json
  def index
    @data_list_lines = @data_list.data_list_lines
  end

  # GET /data_list_lines/1
  # GET /data_list_lines/1.json
  def show
  end

  # GET /data_list_lines/new
  def new
    @data_list_line = @data_list.data_list_lines.build
  end

  # GET /data_list_lines/1/edit
  def edit
  end

  # POST /data_list_lines
  # POST /data_list_lines.json
  def create
    @data_list_line = @data_list.data_list_lines.build(data_list_line_params)

    respond_to do |format|
      if @data_list_line.save
        format.html { redirect_to data_list_data_list_lines_url(@data_list), notice: 'Data list line was successfully created.' }
        format.json { render :show, status: :created, location: [@data_list, @data_list_line] }
      else
        format.html { render :new }
        format.json { render json: @data_list_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_list_lines/1
  # PATCH/PUT /data_list_lines/1.json
  def update
    @data_list = DataList.find(params[:data_list_id])
    respond_to do |format|
      if @data_list_line.update(data_list_line_params)
        format.html { redirect_to data_list_data_list_lines_url(@data_list), notice: 'Data list line was successfully updated.' }
        format.json { render :show, status: :ok, location: [@data_list, @data_list_line] }
      else
        format.html { render :edit }
        format.json { render json: @data_list_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_list_lines/1
  # DELETE /data_list_lines/1.json
  def destroy
    @data_list_line.destroy
    respond_to do |format|
      format.html { redirect_to data_list_data_list_lines_url(@data_list), notice: 'Data list line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_inheritenced_vars
      @data_list = DataList.find(params[:data_list_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_data_list_line
      @data_list_line = DataListLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_list_line_params
      params.require(:data_list_line).permit(:value)
    end
end

app/helpers/analytes_helper.rb
module AnalytesHelper
end

app/helpers/data_list_lines_helper.rb
module DataListLinesHelper
end

app/helpers/data_lists_helper.rb
module DataListsHelper
end

app/helpers/mode_lists_helper.rb
module ModeListsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/data_list_lines/_form.html.erb
<%= form_with(model: [@data_list, data_list_line], local: true) do |form| %>
  <% if data_list_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_list_line.errors.count, "error") %> prohibited this data_list_line from being saved:</h2>

      <ul>
      <% data_list_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :data_list_line_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_list_lines/edit.html.erb
<h1>Editing Data List Line</h1>

<%= render 'form', data_list_line: @data_list_line %>

<%= link_to 'Show', data_list_data_list_line_path(@data_list, @data_list_line) %> |
<%= link_to 'Back', data_list_data_list_lines_path(@data_list) %>

app/views/data_list_lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data List Lines</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_list_lines.each do |data_list_line| %>
      <tr>
        <td><%= data_list_line.value %></td>
        <td><%= link_to 'Show', data_list_data_list_line_url(@data_list, data_list_line) %></td>
        <td><%= link_to 'Edit', edit_data_list_data_list_line_path(@data_list, data_list_line) %></td>
        <td><%= link_to 'Destroy', [@data_list, data_list_line], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data List Line', new_data_list_data_list_line_path %>

app/views/data_list_lines/new.html.erb
<h1>New Data List Line</h1>

<%= render 'form', data_list_line: @data_list_line %>

<%= link_to 'Back', data_list_data_list_lines_path(@data_list) %>

app/views/data_list_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @data_list_line.value %>
</p>

<%= link_to 'Edit', edit_data_list_data_list_line_path(@data_list, @data_list_line) %> |
<%= link_to 'Back', data_list_data_list_lines_path(@data_list) %>