config/routes.rb
Rails.application.routes.draw do

  resources :programs
  root 'welcome#index'


  devise_for :users


  resources :programs do
	 resources :analytes do
      resources :unit_lists
      resources :data_lists
      resources :mode_lists
      resources :reagent_lists
    end
  end

  resources :unit_lists do
    resources :unit_list_lines
  end

  resources :data_lists do
    resources :data_list_lines
  end

  resources :mode_lists do
    resources :mode_list_lines
  end

  resources :reagent_lists do
    resources :reagent_list_lines
  end
  

end

app/models/analyte.rb
class Analyte < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :program, optional: true
	belongs_to :reagent_list, optional: true
	belongs_to :unit_list, optional: true
	belongs_to :mode_list, optional: true
	belongs_to :data_list, optional: true
end

app/models/data_list.rb
class DataList < ApplicationRecord
	has_many :analytes
	has_many :data_list_lines, dependent: :destroy
end

app/models/data_list_line.rb
class DataListLine < ApplicationRecord
	has_many :data, dependent: :destroy
	has_many :units, dependent: :destroy
	belongs_to :data_list, optional: true
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :term, optional: true
  belongs_to :program, optional: true
  belongs_to :analyte, optional: true
  belongs_to :unit, optional: true
  belongs_to :mode, optional: true
  belongs_to :reagent, optional: true
  belongs_to :data_list_line, optional: true
end

app/models/mode.rb
class Mode < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :mode_list_line, optional: true
end

app/models/mode_list.rb
class ModeList < ApplicationRecord
	has_many :analytes
	has_many :mode_list_lines, dependent: :destroy
end

app/models/mode_list_line.rb
class ModeListLine < ApplicationRecord
	has_many :modes, dependent: :destroy
	belongs_to :mode_list, optional: true
end

app/models/program.rb
class Program < ApplicationRecord
	has_many :data, dependent: :destroy
	has_many :analytes, dependent: :destroy
end

app/models/reagent.rb
class Reagent < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :reagent_list_line, optional: true
end

app/models/reagent_list.rb
class ReagentList < ApplicationRecord
	has_many :analytes
	has_many :reagent_list_lines, dependent: :destroy
end

app/models/reagent_list_line.rb
class ReagentListLine < ApplicationRecord
	has_many :reagents, dependent: :destroy
	belongs_to :reagent_list, optional: true
end

app/models/term.rb
class Term < ApplicationRecord
	has_many :data, dependent: :destroy
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :unit_list_line, optional: true
end

app/models/unit_list.rb
class UnitList < ApplicationRecord
	has_many :analytes
	has_many :unit_list_lines, dependent: :destroy
end

app/models/unit_list_line.rb
class UnitListLine < ApplicationRecord
	belongs_to :unit_list, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :data, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/analytes_controller.rb
class AnalytesController < ApplicationController
  before_action :set_analyte, only: [:show, :edit, :update, :destroy]
  before_action :set_inheritenced_vars, only: [:index, :show, :edit, :new, :create, :update, :destroy]

  # GET /analytes
  # GET /analytes.json
  def index
    @analytes = @program.analytes
  end

  # GET /analytes/1
  # GET /analytes/1.json
  def show
  end

  # GET /analytes/new
  def new
    @analyte = @program.analytes.build
  end

  # GET /analytes/1/edit
  def edit
  end

  # POST /analytes
  # POST /analytes.json
  def create
    @analyte = @program.analytes.build(analyte_params)

    respond_to do |format|
      if @analyte.save
        format.html { redirect_to program_analytes_url(@program), notice: 'Analyte was successfully created.' }
        format.json { render :show, status: :created, location: @analyte }
      else
        format.html { render :new }
        format.json { render json: @analyte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /analytes/1
  # PATCH/PUT /analytes/1.json
  def update
    respond_to do |format|
      if @analyte.update(analyte_params)
        format.html { redirect_to program_analytes_url(@program), notice: 'Analyte was successfully updated.' }
        format.json { render :show, status: :ok, location: @analyte }
      else
        format.html { render :edit }
        format.json { render json: @analyte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analytes/1
  # DELETE /analytes/1.json
  def destroy
    @analyte.destroy
    respond_to do |format|
      format.html { redirect_to program_analytes_url(@program), notice: 'Analyte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_inheritenced_vars
      if params[:program_id] != nil
        @program = Program.find(params[:program_id])
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_analyte
      @analyte = Analyte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def analyte_params
      params.require(:analyte).permit(:name)
    end
end

app/helpers/analytes_helper.rb
module AnalytesHelper
end

app/helpers/data_lists_helper.rb
module DataListsHelper
end

app/helpers/mode_lists_helper.rb
module ModeListsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/unit_lists_helper.rb
module UnitListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/analytes/_form.html.erb
<%= form_with(model: [@program, analyte], local: true) do |form| %>
  <% if analyte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(analyte.errors.count, "error") %> prohibited this analyte from being saved:</h2>

      <ul>
      <% analyte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :analyte_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/analytes/edit.html.erb
<h1>Editing Analyte</h1>

<%= render 'form', analyte: @analyte %>

<%= link_to 'Back', program_analytes_url(@program)%>

app/views/analytes/index.html.erb
<h2 align="center">Analitler</h2></br>
<% @analytes.each do |analyte| %>
  <div class="col-md-4">
    <div align="center" class="message">
          <h2 align="center" class="message-title"><%= link_to analyte.name, program_analyte_path(@program, analyte) %></h2>
          <div class="btn-group" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-default"><%= link_to 'Unit List', analyte.unit_list == nil ? new_program_analyte_unit_list_path(@program, analyte) : program_analyte_unit_list_path(@program, analyte, analyte.unit_list)%></button>
            <button type="button" class="btn btn-default"><%= link_to 'Mode List', analyte.mode_list == nil ? new_program_analyte_mode_list_path(@program, analyte) : program_analyte_mode_list_path(@program, analyte, analyte.mode_list)%></button>
            <button type="button" class="btn btn-default"><%= link_to 'Reagent List', analyte.reagent_list == nil ? new_program_analyte_reagent_list_path(@program, analyte) : program_analyte_reagent_list_path(@program, analyte, analyte.reagent_list)%></button>
          <div class="text-center">
            <button type="button" class="btn btn-default"><%= link_to 'Data List', analyte.data_list == nil ? new_program_analyte_data_list_path(@program, analyte) : program_analyte_data_list_path(@program, analyte, analyte.data_list)%></button>
          </div>
        </div>
    </div>
  </div>
<% end %>
<div class="col-md-4">
  <div align="center" class="message">
    <h1 align="center" class="message-title">
      <button type="button" class="btn btn-secondary btn-lg btn-block">
        <%= link_to 'Yeni Analit Oluştur', new_program_analyte_path %>
      </button>
    </h1>
    <h2 align="center" class="message-title">
      <button type="button" class="btn btn-secondary btn-lg btn-block">
      <%= link_to 'Programlara Dön', {controller: "programs", action: "index" } %>
      </button>
    </h2>
  </div>
</div>

app/views/analytes/new.html.erb
<h1>New Analyte</h1>

<%= render 'form', analyte: @analyte %>

<%= link_to 'Back', [@program, @analyte] %>

app/views/analytes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @analyte.name %>
</p>
<div class="btn-group" role="group" aria-label="Basic example">
  <button type="button" class="btn btn-secondary"><%= link_to 'Edit', edit_program_analyte_path(@program, @analyte)%></button>
  <button type="button" class="btn btn-secondary"><%= link_to 'Destroy', [@program, @analyte], method: :delete, data: { confirm: 'Are you sure?' } %></button>
  <button type="button" class="btn btn-secondary"><%= link_to 'Back', program_analytes_url(@program) %></button>
</div>