config/routes.rb
Rails.application.routes.draw do

  resources :programs
  root 'welcome#index'


  devise_for :users


  resources :programs do
	 resources :analytes do
      resources :unit_lists
      resources :data_lists
      resources :mode_lists
      resources :reagent_lists
    end
  end

  resources :unit_lists do
    resources :unit_list_lines
  end

  resources :data_lists do
    resources :data_list_lines
  end

  resources :mode_lists do
    resources :mode_list_lines
  end

  resources :reagent_lists do
    resources :reagent_list_lines
  end
  

end

app/models/analyte.rb
class Analyte < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :program, optional: true
	belongs_to :reagent_list, optional: true
	belongs_to :unit_list, optional: true
	belongs_to :mode_list, optional: true
	belongs_to :data_list, optional: true
end

app/models/data_list.rb
class DataList < ApplicationRecord
	has_many :analytes
	has_many :data_list_lines, dependent: :destroy
end

app/models/data_list_line.rb
class DataListLine < ApplicationRecord
	has_many :data, dependent: :destroy
	has_many :units, dependent: :destroy
	belongs_to :data_list, optional: true
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :term, optional: true
  belongs_to :program, optional: true
  belongs_to :analyte, optional: true
  belongs_to :unit, optional: true
  belongs_to :mode, optional: true
  belongs_to :reagent, optional: true
  belongs_to :data_list_line, optional: true
end

app/models/mode.rb
class Mode < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :mode_list_line, optional: true
end

app/models/mode_list.rb
class ModeList < ApplicationRecord
	has_many :analytes
	has_many :mode_list_lines, dependent: :destroy
end

app/models/mode_list_line.rb
class ModeListLine < ApplicationRecord
	has_many :modes, dependent: :destroy
	belongs_to :mode_list, optional: true
end

app/models/program.rb
class Program < ApplicationRecord
	has_many :data, dependent: :destroy
	has_many :analytes, dependent: :destroy
end

app/models/reagent.rb
class Reagent < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :reagent_list_line, optional: true
end

app/models/reagent_list.rb
class ReagentList < ApplicationRecord
	has_many :analytes
	has_many :reagent_list_lines, dependent: :destroy
end

app/models/reagent_list_line.rb
class ReagentListLine < ApplicationRecord
	has_many :reagents, dependent: :destroy
	belongs_to :reagent_list, optional: true
end

app/models/term.rb
class Term < ApplicationRecord
	has_many :data, dependent: :destroy
end

app/models/unit.rb
class Unit < ApplicationRecord
	has_many :data, dependent: :destroy
	belongs_to :unit_list_line, optional: true
end

app/models/unit_list.rb
class UnitList < ApplicationRecord
	has_many :analytes
	has_many :unit_list_lines, dependent: :destroy
end

app/models/unit_list_line.rb
class UnitListLine < ApplicationRecord
	belongs_to :unit_list, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :data, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/reagent_lists_controller.rb
class ReagentListsController < ApplicationController
  before_action :set_reagent_list, only: [:show, :edit, :update, :destroy]
  before_action :set_inheritenced_vars, only: [:show, :edit,:new, :create, :update, :destroy]

  # GET /reagent_lists
  # GET /reagent_lists.json
  def index
    @reagent_lists = ReagentList.all
  end

  # GET /reagent_lists/1
  # GET /reagent_lists/1.json
  def show
  end

  # GET /reagent_lists/new
  def new
    @reagent_list = ReagentList.new
  end

  # GET /reagent_lists/1/edit
  def edit
  end

  # POST /reagent_lists
  # POST /reagent_lists.json
  def create
    @reagent_list = ReagentList.new(reagent_list_params)

    respond_to do |format|
      if @reagent_list.save
        if params[:program_id] != nil
          @analyte.reagent_list_id = @reagent_list.id
          @analyte.save
          format.html { redirect_to program_analyte_reagent_list_path(@program, @analyte, @reagent_list), notice: 'Reagent list was successfully created.' }
          format.json { render :show, status: :created, location: [@program, @analyte, @reagent_list] }
        else
          format.html { redirect_to reagent_list_path(@reagent_list), notice: 'Reagent list was successfully created.' }
          format.json { render :show, status: :created, location: @reagent_list }
        end
      else
        format.html { render :new }
        format.json { render json: @reagent_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reagent_lists/1
  # PATCH/PUT /reagent_lists/1.json
  def update
    respond_to do |format|
      if @reagent_list.update(reagent_list_params)
        if params[:program_id] != nil
          format.html { redirect_to program_analyte_reagent_list_path(@program, @analyte, @reagent_list), notice: 'Reagent list was successfully updated.' }
          format.json { render :show, status: :ok, location: [@program, @analyte, @reagent_list] }
        else
          format.html { redirect_to reagent_list_path(@reagent_list), notice: 'Reagent list was successfully updated.' }
          format.json { render :show, status: :created, location: @reagent_list }
        end
      else
        format.html { render :edit }
        format.json { render json: @reagent_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reagent_lists/1
  # DELETE /reagent_lists/1.json
  def destroy
    @reagent_list.destroy
    respond_to do |format|
      if params[:program_id] != nil
        format.html { redirect_to program_analytes_url(@program), notice: 'Mode list was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to reagent_lists_path, notice: 'Reagent list was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    def set_inheritenced_vars
      if params[:program_id] != nil && params[:analyte_id] != nil
        @program = Program.find(params[:program_id])
        @analyte = Analyte.find(params[:analyte_id])
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_reagent_list
      @reagent_list = ReagentList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reagent_list_params
      params.require(:reagent_list).permit(:name)
    end
end

app/helpers/analytes_helper.rb
module AnalytesHelper
end

app/helpers/data_lists_helper.rb
module DataListsHelper
end

app/helpers/mode_lists_helper.rb
module ModeListsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/reagent_lists_helper.rb
module ReagentListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/reagent_lists/_form.html.erb
<%= form_with(model: params[:program_id] != nil ? [@program, @analyte, reagent_list] : reagent_list, local: true) do |form| %>
  <% if reagent_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reagent_list.errors.count, "error") %> prohibited this reagent_list from being saved:</h2>

      <ul>
      <% reagent_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reagent_list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reagent_lists/edit.html.erb
<h1>Editing Reagent List</h1>

<%= render 'form', reagent_list: @reagent_list %>

<%= link_to 'Show', params[:program_id] != nil ? program_analyte_reagent_list_path(@program, @analyte, @reagent_list) : reagent_list_path(@reagent_list) %> |
<%= link_to 'Back', params[:program_id] != nil ? program_analyte_reagent_list_path(@program, @analyte, @reagent_list) : reagent_lists_path %>

app/views/reagent_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reagent Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reagent_lists.each do |reagent_list| %>
      <tr>
        <td><%= link_to reagent_list.name, reagent_list_reagent_list_lines_url(reagent_list) %></td>
        <td><%= link_to 'Show', reagent_list %></td>
        <td><%= link_to 'Edit', edit_reagent_list_path(reagent_list) %></td>
        <td><%= link_to 'Destroy', reagent_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reagent List', new_reagent_list_path %>

app/views/reagent_lists/new.html.erb
<h1>New Reagent List</h1>

<%= render 'form', reagent_list: @reagent_list %>

<%= link_to 'Back', params[:program_id] != nil ? program_analytes_path(@program) : reagent_lists_path %>

app/views/reagent_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reagent_list.name %>
</p>

<%= link_to 'Edit', params[:program_id] != nil ? edit_program_analyte_reagent_list_path(params[:program_id], params[:analyte_id], @reagent_list) : edit_reagent_list_path(@reagent_list) %> |
<%= link_to "back", params[:program_id] != nil ? program_analytes_path(params[:program_id]) : reagent_lists_path %>